// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_motorcontroltab;
void ui_event_maxbutton(lv_event_t * e);
extern lv_obj_t * ui_maxbutton;
extern lv_obj_t * ui_Label2;
void ui_event_homebutton(lv_event_t * e);
extern lv_obj_t * ui_homebutton;
extern lv_obj_t * ui_Label1;
void ui_event_minbutton(lv_event_t * e);
extern lv_obj_t * ui_minbutton;
extern lv_obj_t * ui_Label3;
void ui_event_retractbutton(lv_event_t * e);
extern lv_obj_t * ui_retractbutton;
extern lv_obj_t * ui_Label4;
void ui_event_extendbutton(lv_event_t * e);
extern lv_obj_t * ui_extendbutton;
extern lv_obj_t * ui_Label6;
void ui_event_centerbutton(lv_event_t * e);
extern lv_obj_t * ui_centerbutton;
extern lv_obj_t * ui_Label5;
void ui_event_downbutton(lv_event_t * e);
extern lv_obj_t * ui_downbutton;
extern lv_obj_t * ui_Label7;
void ui_event_upbutton(lv_event_t * e);
extern lv_obj_t * ui_upbutton;
extern lv_obj_t * ui_Label8;

extern lv_obj_t * ui_sgresultx;
extern lv_obj_t * ui_sgresulty;
extern lv_obj_t * ui_sgresultxlabel;
extern lv_obj_t * ui_sgresultylabel;
extern lv_obj_t * ui_sgresultycheckbox;
extern lv_obj_t * ui_sgresultxcheckbox;
extern lv_obj_t * ui_infotab;
extern lv_obj_t * ui_settingstab;
void ui_event_restartbutton(lv_event_t * e);
extern lv_obj_t * ui_restartbutton;
extern lv_obj_t * ui_Label9;
void ui_event_screenbrightnessslider(lv_event_t * e);
extern lv_obj_t * ui_screenbrightnessslider;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_roscomcheckbox;
extern lv_obj_t * ui_sd1checkbox;
extern lv_obj_t * ui_sd2checkbox;
extern lv_obj_t * ui_positionpanel;
extern lv_obj_t * ui_wantedlabel;
extern lv_obj_t * ui_wantedpositionlabel;
extern lv_obj_t * ui_actuallabel;
extern lv_obj_t * ui_actualpositionlabel;
extern lv_obj_t * ui_motorenablepanel;
void ui_event_motorenableswitch(lv_event_t * e);
extern lv_obj_t * ui_motorenableswitch;
extern lv_obj_t * ui_motorenablelabel;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
