// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void maxbutton_clicked(lv_event_t * e);
void homebutton_clicked(lv_event_t * e);
void minbutton_clicked(lv_event_t * e);
void retractbutton_clicked(lv_event_t * e);
void extendbutton_clicked(lv_event_t * e);
void centerbutton_clicked(lv_event_t * e);
void downbutton_clicked(lv_event_t * e);
void upbutton_clicked(lv_event_t * e);
void stallguardvalue_changed(lv_event_t * e);
void restartbutton_pressed(lv_event_t * e);
void brightness_changed(lv_event_t * e);
void moterenable_switched(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
