// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui


#include <WiFi.h>
#include "ui.h"
#include <lvgl.h>
#include "MotorControl.h"
#include "GlobalVariables.h"
#include "Homing.h"

bool motor_enable = true;
bool home_check = false;

void maxbutton_clicked(lv_event_t * e)
{
	wanted_position[0] = x_max;
	wanted_position[1] = y_max;
	move_motors();
}

void homebutton_clicked(lv_event_t * e)
{
	home_axis();
}

void minbutton_clicked(lv_event_t * e)
{
	wanted_position[0] = x_min;
	wanted_position[1] = y_min;
	move_motors();
}

void retractbutton_clicked(lv_event_t * e)
{
	move_delta(0,  -100);
}

void extendbutton_clicked(lv_event_t * e)
{
	move_delta(0,  100);
}

void centerbutton_clicked(lv_event_t * e)
{
	wanted_position[0] = (x_max/2);
	wanted_position[1] = (y_max/2);
	move_motors();
}

void downbutton_clicked(lv_event_t * e)
{
	move_delta(1,  -100);
}

void upbutton_clicked(lv_event_t * e)
{
	move_delta(1,  100);
}

void restartbutton_pressed(lv_event_t * e)
{
	ESP.restart();
}

void brightness_changed(lv_event_t * e)
{

    lv_obj_t * slider_brightness = lv_event_get_target(e);
    int slider_value_brightness = lv_slider_get_value(slider_brightness);
    int brightness = slider_value_brightness;
	ledcWrite(0, brightness);
}

void moterenable_switched(lv_event_t * e) {
    lv_obj_t * switch_obj = lv_event_get_target(e);
    bool switch_state = lv_obj_has_state(switch_obj, LV_STATE_CHECKED);

    if (switch_state) {
        motor_enable = true;
    } else {
        motor_enable = false;
    }
}
