// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 480);
    lv_obj_set_height(ui_TabView1, 320);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_motorcontroltab = lv_tabview_add_tab(ui_TabView1, "Motor Control");
    lv_obj_clear_flag(ui_motorcontroltab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_maxbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_maxbutton, 60);
    lv_obj_set_height(ui_maxbutton, 60);
    lv_obj_set_x(ui_maxbutton, 200);
    lv_obj_set_y(ui_maxbutton, -85);
    lv_obj_set_align(ui_maxbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_maxbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_maxbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_maxbutton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Max");

    ui_homebutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_homebutton, 60);
    lv_obj_set_height(ui_homebutton, 60);
    lv_obj_set_x(ui_homebutton, 200);
    lv_obj_set_y(ui_homebutton, -20);
    lv_obj_set_align(ui_homebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_homebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_homebutton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Home");

    ui_minbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_minbutton, 60);
    lv_obj_set_height(ui_minbutton, 60);
    lv_obj_set_x(ui_minbutton, 200);
    lv_obj_set_y(ui_minbutton, 45);
    lv_obj_set_align(ui_minbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_minbutton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Min");

    ui_retractbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_retractbutton, 60);
    lv_obj_set_height(ui_retractbutton, 60);
    lv_obj_set_x(ui_retractbutton, 125);
    lv_obj_set_y(ui_retractbutton, -20);
    lv_obj_set_align(ui_retractbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_retractbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_retractbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_retractbutton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Retract");

    ui_extendbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_extendbutton, 60);
    lv_obj_set_height(ui_extendbutton, 60);
    lv_obj_set_x(ui_extendbutton, -5);
    lv_obj_set_y(ui_extendbutton, -20);
    lv_obj_set_align(ui_extendbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extendbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_extendbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_extendbutton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Extend");

    ui_centerbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_centerbutton, 60);
    lv_obj_set_height(ui_centerbutton, 60);
    lv_obj_set_x(ui_centerbutton, 60);
    lv_obj_set_y(ui_centerbutton, -20);
    lv_obj_set_align(ui_centerbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_centerbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_centerbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_centerbutton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Center");

    ui_downbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_downbutton, 60);
    lv_obj_set_height(ui_downbutton, 60);
    lv_obj_set_x(ui_downbutton, 60);
    lv_obj_set_y(ui_downbutton, 45);
    lv_obj_set_align(ui_downbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_downbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_downbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_downbutton);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Down");

    ui_upbutton = lv_btn_create(ui_motorcontroltab);
    lv_obj_set_width(ui_upbutton, 60);
    lv_obj_set_height(ui_upbutton, 60);
    lv_obj_set_x(ui_upbutton, 60);
    lv_obj_set_y(ui_upbutton, -85);
    lv_obj_set_align(ui_upbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_upbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_upbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_upbutton);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Up");

    ui_sgresultx = lv_label_create(ui_motorcontroltab);
    lv_obj_set_width(ui_sgresultx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresultx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresultx, -170);
    lv_obj_set_y(ui_sgresultx, 90);
    lv_obj_set_align(ui_sgresultx, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sgresultx, "NaN");

    ui_sgresulty = lv_label_create(ui_motorcontroltab);
    lv_obj_set_width(ui_sgresulty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresulty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresulty, -171);
    lv_obj_set_y(ui_sgresulty, 115);
    lv_obj_set_align(ui_sgresulty, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sgresulty, "NaN");

    ui_sgresultxlabel = lv_label_create(ui_motorcontroltab);
    lv_obj_set_width(ui_sgresultxlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresultxlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresultxlabel, -208);
    lv_obj_set_y(ui_sgresultxlabel, 90);
    lv_obj_set_align(ui_sgresultxlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sgresultxlabel, "SG_X:");

    ui_sgresultylabel = lv_label_create(ui_motorcontroltab);
    lv_obj_set_width(ui_sgresultylabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresultylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresultylabel, -208);
    lv_obj_set_y(ui_sgresultylabel, 115);
    lv_obj_set_align(ui_sgresultylabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sgresultylabel, "SG_Y:");

    ui_sgresultycheckbox = lv_checkbox_create(ui_motorcontroltab);
    lv_checkbox_set_text(ui_sgresultycheckbox, "");
    lv_obj_set_width(ui_sgresultycheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresultycheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresultycheckbox, -133);
    lv_obj_set_y(ui_sgresultycheckbox, 115);
    lv_obj_set_align(ui_sgresultycheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sgresultycheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sgresultycheckbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_sgresultxcheckbox = lv_checkbox_create(ui_motorcontroltab);
    lv_checkbox_set_text(ui_sgresultxcheckbox, "");
    lv_obj_set_width(ui_sgresultxcheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sgresultxcheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sgresultxcheckbox, -133);
    lv_obj_set_y(ui_sgresultxcheckbox, 90);
    lv_obj_set_align(ui_sgresultxcheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sgresultxcheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sgresultxcheckbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_infotab = lv_tabview_add_tab(ui_TabView1, "Info Screen");

    ui_settingstab = lv_tabview_add_tab(ui_TabView1, "Settings");

    ui_restartbutton = lv_btn_create(ui_settingstab);
    lv_obj_set_width(ui_restartbutton, 60);
    lv_obj_set_height(ui_restartbutton, 60);
    lv_obj_set_align(ui_restartbutton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_restartbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_restartbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_restartbutton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Restart");

    ui_screenbrightnessslider = lv_slider_create(ui_settingstab);
    lv_slider_set_range(ui_screenbrightnessslider, 10, 255);
    lv_obj_set_width(ui_screenbrightnessslider, 244);
    lv_obj_set_height(ui_screenbrightnessslider, 15);
    lv_obj_set_x(ui_screenbrightnessslider, 60);
    lv_obj_set_y(ui_screenbrightnessslider, 105);
    lv_obj_set_align(ui_screenbrightnessslider, LV_ALIGN_CENTER);


    ui_Label10 = lv_label_create(ui_settingstab);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -149);
    lv_obj_set_y(ui_Label10, 106);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Screen Brightness");

    ui_roscomcheckbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_roscomcheckbox, "ROS COM");
    lv_obj_set_width(ui_roscomcheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roscomcheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roscomcheckbox, 10);
    lv_obj_set_y(ui_roscomcheckbox, 55);
    lv_obj_add_flag(ui_roscomcheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_roscomcheckbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_sd1checkbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_sd1checkbox, "SD1 COM");
    lv_obj_set_width(ui_sd1checkbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd1checkbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd1checkbox, 10);
    lv_obj_set_y(ui_sd1checkbox, 80);
    lv_obj_add_flag(ui_sd1checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sd1checkbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_sd2checkbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_sd2checkbox, "SD2 COM");
    lv_obj_set_width(ui_sd2checkbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd2checkbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd2checkbox, 10);
    lv_obj_set_y(ui_sd2checkbox, 105);
    lv_obj_add_flag(ui_sd2checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sd2checkbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_positionpanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_positionpanel, 183);
    lv_obj_set_height(ui_positionpanel, 60);
    lv_obj_set_x(ui_positionpanel, -140);
    lv_obj_set_y(ui_positionpanel, 5);
    lv_obj_set_align(ui_positionpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_positionpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wantedlabel = lv_label_create(ui_positionpanel);
    lv_obj_set_width(ui_wantedlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wantedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wantedlabel, -50);
    lv_obj_set_y(ui_wantedlabel, -10);
    lv_obj_set_align(ui_wantedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wantedlabel, "Wanted");

    ui_wantedpositionlabel = lv_label_create(ui_positionpanel);
    lv_obj_set_width(ui_wantedpositionlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wantedpositionlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wantedpositionlabel, 40);
    lv_obj_set_y(ui_wantedpositionlabel, -10);
    lv_obj_set_align(ui_wantedpositionlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wantedpositionlabel, "NaN/NaN");

    ui_actuallabel = lv_label_create(ui_positionpanel);
    lv_obj_set_width(ui_actuallabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_actuallabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_actuallabel, -50);
    lv_obj_set_y(ui_actuallabel, 15);
    lv_obj_set_align(ui_actuallabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_actuallabel, "Actual");

    ui_actualpositionlabel = lv_label_create(ui_positionpanel);
    lv_obj_set_width(ui_actualpositionlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_actualpositionlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_actualpositionlabel, 40);
    lv_obj_set_y(ui_actualpositionlabel, 10);
    lv_obj_set_align(ui_actualpositionlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_actualpositionlabel, "NaN/NaN");

    ui_motorenablepanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_motorenablepanel, 183);
    lv_obj_set_height(ui_motorenablepanel, 60);
    lv_obj_set_x(ui_motorenablepanel, -140);
    lv_obj_set_y(ui_motorenablepanel, 70);
    lv_obj_set_align(ui_motorenablepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_motorenablepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_motorenableswitch = lv_switch_create(ui_motorenablepanel);
    lv_obj_set_width(ui_motorenableswitch, 50);
    lv_obj_set_height(ui_motorenableswitch, 25);
    lv_obj_set_x(ui_motorenableswitch, -50);
    lv_obj_set_y(ui_motorenableswitch, 0);
    lv_obj_set_align(ui_motorenableswitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_motorenableswitch, LV_STATE_CHECKED);       /// States


    ui_motorenablelabel = lv_label_create(ui_motorenablepanel);
    lv_obj_set_width(ui_motorenablelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_motorenablelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_motorenablelabel, 35);
    lv_obj_set_y(ui_motorenablelabel, 0);
    lv_obj_set_align(ui_motorenablelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_motorenablelabel, "Enable Motor");

    lv_obj_add_event_cb(ui_maxbutton, ui_event_maxbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homebutton, ui_event_homebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minbutton, ui_event_minbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_retractbutton, ui_event_retractbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_extendbutton, ui_event_extendbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_centerbutton, ui_event_centerbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_downbutton, ui_event_downbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_upbutton, ui_event_upbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_restartbutton, ui_event_restartbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenbrightnessslider, ui_event_screenbrightnessslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_motorenableswitch, ui_event_motorenableswitch, LV_EVENT_ALL, NULL);

}
